const data = {
  tables: [
    { name: "Table1", seats: 4, status: "available" },
    { name: "Table1", seats: 4, status: "available" },
    { name: "Table1", seats: 4, status: "available" },
    { name: "Table1", seats: 4, status: "available" },
    { name: "Table1", seats: 4, status: "available" },
    { name: "Table1", seats: 4, status: "available" },
    { name: "Table1", seats: 4, status: "available" },
    { name: "Table1", seats: 4, status: "available" },
    { name: "Table1", seats: 4, status: "available" },
    { name: "Table1", seats: 4, status: "available" },
    { name: "Table1", seats: 4, status: "available" },
    { name: "Table1", seats: 4, status: "available" },
    { name: "Table1", seats: 4, status: "available" },
    { name: "Table1", seats: 4, status: "available" },
    { name: "Table1", seats: 4, status: "available" },
  ],
  categories: [
    { _id: "01", name: "ເຄື່ອງດື່ມ" },
    { _id: "02", name: "ຕາມສັ່ງ" },
    { _id: "03", name: "ຈຸ່ມດາດ" },
    { _id: "04", name: "ຕຳ" },
    { _id: "05", name: "ປີ້ງ" },
    { _id: "06", name: "ທອດ" },
    { _id: "07", name: "ຍຳ" },
    { _id: "08", name: "ຕົ້ມ-ແກງ" },
    { _id: "09", name: "ລວກ" },
    { _id: "10", name: "ລາບ-ກ້ອຍ" },
  ],
  units: [
    { _id: "01", name: "ແກ້ວ" },
    { _id: "02", name: "ຈານ" },
    { _id: "03", name: "ຖ້ວຍ" },
    { _id: "05", name: "ຊຸດ" },
    { _id: "06", name: "ຈອກ" },
    { _id: "07", name: "ກະຕ່າ" },
  ],
  ingredients: [
    { _id: "01", name: "ເຂົ້າ" },
    { _id: "02", name: "ໄຂ່" },
    { _id: "03", name: "ຊີ້ນງົວ" },
    { _id: "04", name: "ຊີ້ນໝູ" },
    { _id: "05", name: "ທະເລ" },
    { _id: "06", name: "ປາ" },
  ],
  foods: [
    {
      _id: "01",
      name: "ເບຍລາວໃຫຍ່fdsafdsafdsafdsafdsafdsaf",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: true,
      ingredientIDs: [],
    },
    {
      _id: "02",
      name: "ເປບຊີໃຫຍ່",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: true,
      ingredientIDs: [],
    },
    {
      _id: "03",
      name: "ເຂົ້າຜັດໝູ",
      catID: "02",
      unitID: "02",
      price: 25000,
      isFavarite: true,
      ingredientIDs: ["04", "01"],
    },
    {
      _id: "04",
      name: "ຜັດເຜັດໝູ",
      catID: "02",
      unitID: "02",
      price: 55000,
      isFavarite: false,
      ingredientIDs: ["04"],
    },
    {
      _id: "05",
      name: "ງົວຜັດພິກໄທດຳ",
      catID: "02",
      unitID: "02",
      price: 65000,
      isFavarite: false,
      ingredientIDs: ["03"],
    },
    {
      _id: "06",
      name: "ກາດນາໝູກອບ",
      catID: "02",
      unitID: "02",
      price: 50000,
      isFavarite: true,
      ingredientIDs: ["04"],
    },
    {
      _id: "07",
      name: "ຫອຍລາຍຜັດພິກເຜົາ",
      catID: "02",
      unitID: "02",
      price: 40000,
      isFavarite: false,
      ingredientIDs: ["05"],
    },
    {
      _id: "08",
      name: "ປາໜຶ້ງໝາກນາວ",
      catID: "02",
      unitID: "02",
      price: 65000,
      isFavarite: true,
      ingredientIDs: ["06"],
    },
    {
      _id: "09",
      name: "ງົວ+ຜັກ",
      catID: "03",
      unitID: "05",
      price: 58000,
      isFavarite: true,
      ingredientIDs: ["03"],
    },
    {
      _id: "10",
      name: "ທະເລ+ຜັກ",
      catID: "03",
      unitID: "05",
      price: 75000,
      isFavarite: true,
      ingredientIDs: ["05"],
    },
    {
      _id: "11",
      name: "ສາມຊັ້ນ",
      catID: "03",
      unitID: "02",
      price: 40000,
      isFavarite: true,
      ingredientIDs: ["04"],
    },
    {
      _id: "12",
      name: "ໝູລວມ",
      catID: "03",
      unitID: "02",
      price: 40000,
      isFavarite: false,
      ingredientIDs: ["04"],
    },
    {
      _id: "13",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "14",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "15",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "16",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "17",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "18",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "19",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "20",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "21",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "22",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "23",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "24",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "25",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "26",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "27",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "28",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "29",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "30",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "31",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
    {
      _id: "32",
      name: "Beerlao Big",
      catID: "01",
      unitID: "01",
      price: 15000,
      isFavarite: false,
      ingredientIDs: [],
    },
  ],
};

export default data;
